internal/driver/deviceclient_test.go

Add unit test for data bytes transformation function

---

internal/driver/driver.go

Fix #14 
Add address lock to avoid concurrency issue because the real device didn't handle multiple requests at a time

Add address lock to avoid concurrency issue

---

internal/driver/driver.go

Optimize address lock function to avoid concurrency error

---

internal/driver/deviceclient.go
internal/driver/deviceclient_test.go

Replace ParseInt with ParseUint to fix unitID out of rage

---

internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/modbusclient.go

 Check high-frequency command execution to avoid goroutine block

---

cmd/res/configuration.toml
cmd/res/docker/configuration.toml

Follow up changes for issue #22  based on Lenny's comment.

Updating non-docker toml files to match with docker version

---

cmd/res/example/configuration.toml
go.mod
internal/driver/config.go
internal/driver/config_test.go
internal/driver/deviceclient.go
internal/driver/deviceclient_test.go
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/modbusclient.go
internal/driver/protocolpropertykey.go

Fix #30 
Updated to the replacement of Device.Addressable with Device Protocols, and the deprecation of Schedule* objects by device-sdk-go

Updated to the replacement of Device.Addressable with Device Protocols

---

go.mod
internal/driver/deviceclient_test.go
internal/driver/driver.go
internal/driver/driver_test.go

Change import package name logging to logger

---

cmd/res/example/configuration.toml
cmd/res/example/modbus.test.device.profile.yml
go.mod

Update device-sdk-go and add AutoEvents to example

---

Makefile

Remove make prepare target from the Makefile

---

README.md
go.mod
internal/driver/attributechecker.go
internal/driver/attributechecker_test.go
internal/driver/constant.go
internal/driver/deviceclient.go
internal/driver/deviceclient_test.go
internal/driver/driver.go

Update to meet CommandValue and CommandRequest refactoring

---

go.mod

Upgrade the lib to use the latest device-sdk and core-contract
Fix #49

Upgrade to the latest device-sdk and core-contract

---

cmd/res/configuration.toml
cmd/res/docker/configuration.toml
cmd/res/example/configuration.toml
go.mod

Remove ReadMaxLimit and update config

---

cmd/res/configuration.toml
cmd/res/docker/configuration.toml
cmd/res/example/configuration.toml
go.mod

[edinburgh] Remove ReadMaxLimit and update config

---

snap/snapcraft.yaml

Forward-port of #66 to master for Fuji

Specify consul addr in registry arg in snap

---

.gitignore
Makefile

Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>

Add code coverage output file

---

go.mod
internal/driver/driver.go

Fix #82 
Update to the Latest Version of device-sdk-go and go-mod-core-contracts.

Update Device Service to Latest Version of Device SDK

---

Dockerfile

Fix #85 
Add flag "--registry=consul://edgex-core-consul:8500" to the Dockerfile ENTRYPOINT.

Use registry running in docker

---

cmd/res/example/modbus.test.device.profile.yml
go.mod

Update go.mod: Update device SDK to the latest version
Update device profile:
- Replace "object" with "deviceResource"
- Remove "parameter" fields from get commands
- Replace 503 error code with 500
fix #89

Update sdk version and device profile.

---

go.mod

Fix #91 
Update the go.mod according to the SDK change.

Update to the latest SDK version

---

Attribution.txt
Makefile
bin/test-attribution-txt.sh
bin/test-go-mod-tidy.sh
internal/driver/modbusclient.go

Add Attribution file and extend maketest to check it

---

Dockerfile

Add license/copyright labels to the docker container
Fix #113

Add license/copyright labels to container

---

internal/driver/attributechecker.go
internal/driver/attributechecker_test.go
internal/driver/constant.go
internal/driver/deviceclient.go
internal/driver/deviceclient_test.go

Fix #119 
Extract attribute names as constants.

Extract attribute names as constants

---

internal/driver/constant.go
internal/driver/driver.go

Protocol driver should check and wait unfinished job when service stop
Fix #117 
Signed-off-by: weichou <weichou1229@gmail.com>

Check unfinished job when stop

---

internal/driver/caster.go

Fix #121 
Extract common function to check undefined value

Extract common function to check undefined value

---

internal/driver/driver.go

Fix #123
Modify log level and remove unnecessary comment

Modify log level and remove unnecessary comment

---

internal/driver/driver.go

Fix #125 
Remove unnecessary signature

Remove unnecessary signature

---

go.mod

Fix #148 
Signed-off-by: Chris Hung <chris@iotechsys.com>

upgrade sdk version to v1.2.1 for geneva release

---

cmd/res/configuration.toml
cmd/res/example/configuration.toml
go.mod

fix #157 
fix #158 
upgrade SDK to v1.2.3, remove ClientMonitor field and
add ServerBindAddr field in configuration.toml
Signed-off-by: Chris Hung <chris@iotechsys.com>

Update SDK version and configuration file

---

Dockerfile

Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/device-modbus-go/issues/163

refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#163

---

simulator/README.md
simulator/go.mod
simulator/main.go

Fix #161
Issue Number: #161 
- Create a default simulator with port 1502
- Create simulators for scalability test

feat: Modify Modbus simulator to support device scaling

---

README.md

Signed-off-by: weichou <weichou1229@gmail.com>
Issue Number: #161 
Update the README.md to add document path

docs: Update the Modbus simulator's README.md

---

Attribution.txt
Dockerfile
Dockerfile.build
Jenkinsfile
bin/test-attribution-txt.sh
go.mod
snap/snapcraft.yaml

fix #173 
Signed-off-by: Chris Hung <chris@iotechsys.com>

build: Upgrade to Go1.15

---

go.mod

fix #192 
Signed-off-by: Felix Ting <felix@iotechsys.com>
- Bumps github.com/edgexfoundry/device-sdk-go from v1.3.0 to v1.3.1-dev.4
- Bumps github.com/edgexfoundry/go-mod-core-contracts from v0.1.111 to v0.1.115

build: update device-sdk-go to v1.3.1-dev.4

---

Jenkinsfile

Fix #196
Signed-off-by: weichou <weichou1229@gmail.com>
- [x ] CI related changes
Issue Number: #196
Since we modify the simulator to support scalability test, it need upgrade the version for docker image.

feat: Upgrade modbus simulator version to 1.0.0

---

go.mod

Fix #212
The sdk version is v1.3.1-dev.11
Issue Number: #212 
Upgrade the sdk version to v1.4.0

build: Upgrade sdk version to 1.4.0

---

cmd/res/configuration.toml
cmd/res/example/configuration.toml

Support logging has been removed so now the configuration is obsolete.
Issue Number: #204 
Removed the following sections from configuration.toml:
- [Logging]
- [Clients.Logging]
fix: #204

feat: Remove Logging configuration

---

.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Iain Anderson <iain@iotechsys.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/master/.github/CONTRIBUTING.md
Wrong filename in link to Contributing document
Fixed link

ci: fix link to Contributing.md

---

cmd/res/example/configuration.toml
internal/driver/config.go
internal/driver/config_test.go
internal/driver/modbusclient.go
internal/driver/protocolpropertykey.go

Close #108
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-modbus-go/blob/master/.github/CONTRIBUTING.md
Timeout - Connect & Read timeout(seconds)
IdleTimeout - timeout(seconds) to close the connection

feat: Add Timeout and IdleTimeout to Protocol property

---

Dockerfile
Dockerfile.build
snap/snapcraft.yaml

This PR updates the snap and docker builds for go 1.16.
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

fix(build): update snap and docker builds for go116

---

Makefile
cmd/res/configuration.toml
go.mod

no secure MessageBus capability
Secure MessageBus capability added

feat: Add secure MessagBus capability

---

cmd/res/devices/modbus.test.devices.toml

Signed-off-by: Chris Hung <chris@iotechsys.com>

refactor: rename example device AutoEvent Frequency to Interval

---

cmd/res/configuration.toml
go.mod
internal/driver/config.go
internal/driver/config_test.go
internal/driver/constant.go
internal/driver/deviceclient.go
internal/driver/deviceclient_test.go
internal/driver/driver.go
internal/driver/utils.go

refactor: bump dependency version and update import path

---

go.mod

Using old version of SDK
Using latest version of SDK with released go-mod-messaging and latest core-contracts.

build: update to latest SDK

---

GOVERNANCE.md
OWNERS.md
cmd/res/configuration.toml
cmd/res/devices/modbus.test.devices.toml

also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

fix: update all TOML to use quote and not single-quote

---

README.md
snap/README.md

docs(snap): update snap/README and add snap section in README

---

README.md

Add the document link to refer the Modbus RTU usage
Close #182
https://github.com/edgexfoundry/edgex-docs/pull/707

docs: Update README.md for Modbus RTU usage

---

.golangci.yml
Makefile
internal/driver/driver.go
internal/driver/modbusclient.go

fixes:#320
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

feat: enable gosec and default linter set

---

Attribution.txt
go.mod
go.sum
internal/driver/utils.go
internal/driver/utils_test.go

Resolves #364 
Signed-off-by: Jeff Titus <1756049+jrtitus@users.noreply.github.com>
https://github.com/spf13/cast is also used in [device-mqtt-go](https://github.com/edgexfoundry/device-mqtt-go/blob/adfcd8475fa2a20fe672f9c26fef4422551b8595/go.mod#L11)

refactor: prefer spf13/cast to handle attributes

---

Dockerfile
Makefile
go.mod
snap/local/helper-go/go.mod
snap/snapcraft.yaml

Run non-secure EdgeX stack 
Build and run service from command line
Verify logs no errors bootstrapping.

build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

---

.github/dependabot.yml

ci: Change dependabot gomod schedule to daily

---

cmd/res/profiles/modbus.test.device.profile.yml

BREAKING CHANGE:  Update profile Minimum and Maximum to numeric data according to the latest core-contracts changes.

feat!: Update profile Minimum and Maximum to numeric data

---

README.md

docs: Add main branch Warning

---

internal/driver/deviceclient.go

Previously a misstyped or unsupported primaryTable in a resource led to undescriptive log and error message. This commit fixes it
Closes #548
_No, this only adds missing error handling of existing function._
_No, this only adds missing error handling of existing function._
- Start an instance of EdgeX and include the modbus device service (I used edgex-compose: `make gen no-secty ds-modbus` and modified the modbus device service in the `docker-compose.yml` to point to the local docker image of `device-modbus-go` …

fix: handle error if primaryTable is unsupported

---

internal/driver/config.go
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/modbusclient.go

feat: support reuse modbus client

---

internal/driver/config.go
internal/driver/modbusclient.go
internal/driver/protocolpropertykey.go

feat: support Modbus ASCII

---

internal/driver/driver.go

if command failed, remove the Modbus client from the cache to allow re-establish connection next time
fixes #606
- Deploy core services, device-modubs, modbus sim
- Test command, restart modbus-sim, and test command again.

fix: Remove client when command failed

---

cmd/res/profiles/modbus.test.device.profile.yml
internal/driver/deviceclient.go
internal/driver/deviceclient_test.go

feat: Support Modbus register bit decomposition acquisition
