Dockerfile, Makefile, getglide.sh
- include docker build instructions in makefile for device-modbus-go
Signed-off-by: James Gregg <james.r.gregg@intel.com>
=> Updated Makefile for device-modbus-go

cmd/res/example/configuration.toml, cmd/res/example/modbus.test.device.profile.yml, internal/driver/attributechecker.go, internal/driver/attributechecker_test.go, internal/driver/caster.go, internal/driver/deviceclient.go, internal/driver/driver.go
Fix #9 
Add an attribute checker to make sure all requests attribute are valid and then device-modbus can parse interface safely.
=> Check request attribute before convert to other value type

cmd/res/example/modbus.test.device.profile.yml
Remove RO 'property=value' from example device profile, because this attribute was removed from the model.
Fix #39
=> Remove RO 'property=value' from example device profile

cmd/res/example/modbus.test.device.profile.yml
=> Add eNotation and Base64 to device profile example for float encoding

.gitignore, snap/hooks/configure, snap/hooks/install, snap/hooks/pre-refresh, snap/snapcraft.yaml
Fixes #46
The CI jobs for the snap have been created in https://github.com/edgexfoundry/ci-management/pull/371, so this PR is ready to be reviewed.
To test this snap, on a linux machine (can be a virtual machine):
1. Install snapcraft and multipass with `snap install snapcraft --classic` and `snap install multipass --classic --beta`
2. Checkout this branch using git
3. Build the snap by going to the root directory of this project and running `snapcraft`.
4. The build should produce a .snap file named `edgex-device-modbus*.snap`, install this snap with `snap install --dangerous edgex-device-modbus*.snap`
Assuming all of the above works, the snap is installed and the things to check are:
Additionally, if you have access to a system with modbus devices available to test, create a device …
=> Add initial snap packaging

internal/driver/deviceclient.go, internal/driver/deviceclient_test.go
=> Readings should be timestamped in nanoseconds

internal/driver/modbusclient.go
Signed-off-by: Dave Rensberger <davidr@beechwoods.com>
The device-modbus-go code currently assumes that you don’t need to use the “WriteSingleRegister” method in the modbus library (doing a “WriteMultipleRegister” with a parameter of 1 register is NOT the same as WriteSingleRegister at the serial protocol level. For one of my devices, I found this to not hold true. I think this can be fixed without introducing any backward-compatibility issues by making these changes.
Fix #60
=> Adds support for the Modbus WriteSingleRegister command

snap/snapcraft.yaml
As per https://github.com/edgexfoundry/device-sdk-go/pull/274, the
registry arg for device services now needs a value, so use the default
value of consul from the edgexfoundry snap.
Fixes #65
=> Specify consul addr in registry arg in snap

internal/driver/constant.go, internal/driver/deviceclient.go, internal/driver/deviceclient_test.go, internal/driver/driver.go, internal/driver/driver_test.go
Fix #78 
Add rawType attribute to define binary data type
* Read command can use rawType to parse the binary data and use valueType to cast the integer to float. 
* Write command can use rawType to cast the float to integer.
This feature only support :
* integer 16 bits to float.
* float to integer 16 bits
=> Add rawType attribute to define binary data for casting the data type from integer to float

internal/driver/modbusclient.go
Prevent reassign the TCPClientHandler and RTUClientHandler instance to ModbusClient.
Fix #99
=> Fix go vet error

internal/driver/modbusclient.go
Prevent reassign the TCPClientHandler and RTUClientHandler instance to ModbusClient
Fix #99
=> fuji: Fix go vet error

Makefile
=> Fuji: Enable the go vet line in the Makefile

Makefile
Enable the go vet line in the Makefile because of the vet error fixed. https://github.com/edgexfoundry/device-modbus-go/pull/103
Fix #99
=> Enable the go vet line in the Makefile

Dockerfile
Fuji: Add license/copyright labels to the docker container.
Fix #113
=> Fuji: Add license/copyright labels to container

snap/snapcraft.yaml
Update the snap to the 1.1.1.
This has been tested against the latest stable version of the edgexfoundry snap (version: 1.1.0-20200213+5c8c3243, revision: 2049) on an Ubuntu Desktop system running 18.04 LTS.
=> Fuji update snap to 1.1.1

Jenkinsfile
Use current mavenSettings from device-modbus-go.
The maven setting can be found in the Jenkins page
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/device-modbus-go/job/master/4/consoleFull
Fix #135
=> Use current mavenSettings from device-modbus-go

Jenkinsfile, snap/snapcraft.yaml
add `buildSnap:true` option to enable snap builds.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
=> Add new buildSnap option to build snap in Jenkins pipeline

snap/snapcraft.yaml
This change removes the build-time edit of the `configuration.toml` file and instead uses an
environment variable config override to update **Device.ProfilesDir**.
This resolves issue #152.
To test, install the main edgex snap, install the snap built from this PR, start a command to watch log output, and then start the service:
```
$ sudo snap install edgexfoundry
$ sudo snap install edgex-device-modbus_*.snap --dangerous
$ sudo snap logs edgex-device-modbus.device-modbus -f | grep "Environment override"
```
**Note** -- the `--dangerous` flag is used to install an unsigned snap (i.e. a snap that's been built locally).
In another terminal run:
```$ sudo snap start edgex-device-modbus.device-modbus```
You should see the following log message output:
> 2020-06-04T14:46:19Z …
=> snap: add env override for ProfilesDir

internal/driver/deviceclient.go, internal/driver/deviceclient_test.go, internal/driver/swap.go, internal/driver/swap_test.go
Fix #151 
Swap not work for float 32
Issue Number: #151
Fix byte and word swap operation for float32 dataType and add testing.
=> fix: Fix swap operation for float32 dataType

internal/driver/driver.go
fix #164
Signed-off-by: weichou <weichou1229@gmail.com>
Modbus DS use IP to lock address for modbus-tcp.
Issue Number: #164 
Modbus DS combines IP and Port as lockable address for modbus-tcp
=> fix: Lock Modbus TCP address with IP and Port

simulator/README.md, simulator/main.go
Fix #190
Issue Number: #190
Modbus simulator counts the Modbus command amount as the reading amount and provides GET reading amount API for the test requirement.
=> feat: Enhance Modbus simulator to measure reading amount

snap/README.md, snap/local/runtime-helpers/bin/startup-env-var.sh, snap/snapcraft.yaml
1) Add two new configure options:
- To change the default startup duration use:
sudo snap set edgex-device-modbus startup-duration=n
- To change the default startup interval use:
sudo snap set edgex-device-modbus startup-interval=n
2) Update the way version numbers are
generated when building the snap:
- Remove git tag and datestamp from the version number.
('1.1.3-dev.5' vs '1.1.3-dev.4-20201021+856f4f8')
- Use 'snapcraftctl set-version' instead of deprecated 'version-script'
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1) The module go-mod-bootstrap implements a service dependency check on startup which ensures that all of the runtime dependencies of a particular …
=> feat(snap): Add startup configure options and update versioning logic

internal/driver/modbusclient.go
fixes: #180; Return error for write requests to read-only input objects
Signed-off-by: Vijay Annamalaisamy <vijayone1708@gmail.com>
DISCRETES_INPUT and INPUT_REGISTERS are read only registers but are allowed to be writable in the SetValue function
Issue Number: 180
Write requests for DISCRETES_INPUT and INPUT_REGISTERS return error from the SetValue function and writing to these registers can never happen.
No
No
None
=> fix (device services): Remove write of input types

Dockerfile, Makefile, cmd/main.go, cmd/res/configuration.toml, go.mod
**Dependent on edgexfoundry/device-sdk-go#926**
Service key constants have the edgex- prefix
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.
=> refactor: Update for new service key names and overrides for hyphen to underscore

Dockerfile, cmd/res/configuration.toml
closes 
Signed-off-by: lenny <leonard.goodell@intel.com>
Ports assigned for Core/Supporting services are 408xx range
Device Modbus uses 49991
Ports assigned for Core/Supporting services are 588xx range
Device Modbus default port number is now 59901
BREAKING CHANGE: Device Modbus default port number has changed to 59901
=> refactor: Update to assign and uses new Port Assignments

cmd/res/devices/modbus.test.devices.toml, cmd/res/profiles/modbus.test.device.profile.yml
c## PR Checklist
Profile as invalid "." characters in the name
"."s in Profile name changed to "-"s
=> fix: Change "."s in profile name to "-"s

snap/snapcraft.yaml
The makefile requires a VERSION file to be present when building the device service.
This commit creates the file using the current git tag.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1. Build the snap and verify that you see a valid version in
```
CGO_ENABLED=1 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/device-modbus-go.Version=2.0.1-dev.6" -o cmd/device-modbus ./cmd
```
2. Test the REST endpoint at `curl http://localhost:59901/api/v2/version`
=> fix(snap): create VERSION file during snap build

snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/go.mod, snap/local/hooks/go.sum
For details on the new scheme for setting environment variables, please refer to https://github.com/edgexfoundry/edgex-go/pull/3986.
Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-rfid-llrp-inventory/blob/main/.github/Contributing.md
1. Set up:
```
snap install edgexfoundry --edge
snap install edgex-device-modbus --channel=edge/pr-336
```
2. Enable config and set a global config value:
```
$ snap set edgex-device-modbus config-enabled=true
$ snap set edgex-device-modbus config.service-startupmsg="testing injection"
$ snap start …
```
=> feat(snap): add support for env var injection

internal/driver/config.go, internal/driver/config_test.go
fix protocol property timeout and idleTimeout parsing error
Close #438
Run unit test
=> fix: fix protocol properties parsing error

cmd/res/configuration.yaml
Also added comment about overriding seeting via Env Overrides
TBD
Run non-secure EdgeX stack and stop docker version of service if running
Run `make build`
Edit config to uncomment Host values for hybrid mode
Run service locally with `-cp -o` options
Verify no profiles or devices loaded since both settings are setting to  empty string
Stop the service and run the following exports
- `export DEVICE_DEVICESDIR=./res/junk`
- `export DEVICE_PROFILESDIR=./res/junk`
Run service locally again with `-cp -o` options
Verify the following …
=> refactor: Set ProfilesDir & DevicesDir to empty string

cmd/res/devices/modbus.test.devices.yaml
The unmarshaller ignores autoEvents fields because of the casing, resulting in the following fatal error: 
`level=ERROR ts=2023-05-08T14:17:09.982416986Z app=device-modbus source=init.go:95 msg="Failed to load devices: request failed, status code: 400, err: {\"apiVersion\":\"v3\",\"message\":\"AddDeviceRequest.Device.AutoEvents[0].Interval field is required; AddDeviceRequest.Device.AutoEvents[0].SourceName field is required\",\"statusCode\":400}\n"`
This PR changes the cases to camelCase to fix the issue, as suggested by @lenny-intel.
Please check if your PR fulfills the following …
=> fix: change autoEvents keys to camelCase

internal/driver/deviceclient.go, internal/driver/deviceclient_test.go, internal/driver/utils.go
It has been added a new rawType (int32) for the valueType float64.
If the PR is approved, a new PR will be uploaded to update the docs properly
https://docs.edgexfoundry.org/3.0/examples/Ch-ExamplesModbusdatatypeconversion/
-- TestTransformDataBytesToResult_RawType_INT32_ValueType_FLOAT64 in internal/driver/deviceclient_test.go
[ <link to docs PR>](https://github.com/edgexfoundry/edgex-docs/pull/1179)
The UT mentioned above is one way, additionally, It can be tested using the MODBUS simulator
=> feat: rawType int32 for valueType float64 added

internal/driver/constant.go, internal/driver/deviceclient_test.go, internal/driver/modbusclient.go
Since the DISCRETES_INPUT looks like a fairly obvious typo, the best way is to accept both DISCRETE_INPUTS and DISCRETES_INPUT
Run unit test or run device service to verify the DISCRETE_INPUTS is available.
=> feat: Accept DISCRETES_INPUT and DISCRETE_INPUTS as primary table

Makefile
1. Run non-secure edgex stack from compose builder
```
make run no-secty 
```
2. build service from this branch `make build`
3. Verify it builds properly
4. ensure security is off `export EDGEX_SECURITY_SECRET_STORE=false`
5. run service
```
./device-modbus -cp -d -o
```
=> build: [Device Modbus] Add ldflags to strip debug info from binary

internal/driver/driver.go, internal/driver/modbusclient.go
=> fix: Use trace log for details ops

internal/driver/modbusclient.go
Assign the Dial func for TCPClientHandler to fix nil pointer error when sending command.
fix #647
Run core services and device service to test the get and put command.
=> fix: Fix nil pointer error when sending command
